# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["3.8", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test base functionality tool
      run: |
        ena-upload-cli --help
    - name: Create credentials file
      run: |
        echo "username: ${{ secrets.ENA_USERNAME }}" >> .secrets.yaml
        echo "password: ${{ secrets.ENA_PASSWORD }}" >> .secrets.yml
    - name: Test submission in --draft mode
      run: |
        ena-upload-cli --action add --draft --dev --center ${{ secrets.ENA_CENTER }} --data example_data/ENA_TEST1.R1.fastq.gz example_data/ENA_TEST2.R1.fastq.gz example_data/ENA_TEST2.R2.fastq.gz --checklist ERC000033 --secret .secret.yml --xlsx example_tables/ENA_excel_example_ERC000033.xlsx 
    - name: Run Python to get temp directory
      run: |
        echo "TEMP_DIR=$(python -c 'import tempfile; print(tempfile.gettempdir())')" >> $GITHUB_ENV
        echo ${{ env.TEMP_DIR}}
    - uses: actions/upload-artifact@v4
      name: Output XMLs for ${{ matrix.os }} Python ${{ matrix.os }}
      with:
        name: ena-upload-cli_output_${{ matrix.os }}_python_${{ matrix.version }}
        path: ${{ env.TEMP_DIR}}/*.xml
